// <auto-generated />
using System;
using GithubReporterRepository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GithubReporterRepository.Migrations
{
    [DbContext(typeof(GithubReporterContext))]
    [Migration("20260226091426_Refactor_Group_Team_Table")]
    partial class Refactor_Group_Team_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GithubReporterRepository.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GithubEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA586B2A13C03");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.GradePerProject", b =>
                {
                    b.Property<Guid>("GradePerProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GradePerProjectId")
                        .HasName("PK__GradePer__8BEA86BD402B5BED");

                    b.HasIndex(new[] { "ProjectId" }, "IX_GradeOn_ProjectID");

                    b.HasIndex(new[] { "StudentId" }, "IX_GradeOn_StudentID");

                    b.HasIndex(new[] { "StudentId", "ProjectId" }, "UQ_GradePerProject_Student_Project")
                        .IsUnique();

                    b.ToTable("GradePerProject", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.GroupTeam", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectID");

                    b.Property<int>("GroupRole")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId", "ProjectId")
                        .HasName("PK_GroupTeam");

                    b.HasIndex("SupervisorId");

                    b.HasIndex(new[] { "AccountId" }, "IX_GroupTeam_AccountID");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Group_ProjectID");

                    b.ToTable("GroupTeam", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectID");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GithubLink")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId")
                        .HasName("PK__Project__761ABED06E532F3C");

                    b.HasIndex(new[] { "CreatedBy" }, "IX_Project_CreatedBy");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportID");

                    b.Property<int>("CommitAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ProgressByNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectID");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReportId")
                        .HasName("PK__Report__D5BD48E525D98C39");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Report_ProjectID");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A793FC486B2");

                    b.HasIndex("AccountId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Supervisor", b =>
                {
                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SupervisorID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<string>("SupervisorCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("SupervisorId")
                        .HasName("PK__Supervis__6FAABDAF85BD4A61");

                    b.HasIndex("AccountId");

                    b.ToTable("Supervisor", (string)null);
                });

            modelBuilder.Entity("GithubReporterRepository.Models.GradePerProject", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Project", "Project")
                        .WithMany("GradePerProjects")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_GradePerProject_Project");

                    b.HasOne("GithubReporterRepository.Models.Student", "Student")
                        .WithMany("GradePerProjects")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_GradePerProject_Student");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.GroupTeam", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Account", "Account")
                        .WithMany("GroupTeams")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Group_Account");

                    b.HasOne("GithubReporterRepository.Models.Project", "Project")
                        .WithMany("GroupTeams")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Group_Project");

                    b.HasOne("GithubReporterRepository.Models.Supervisor", null)
                        .WithMany("GroupTeams")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Account");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Project", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Account", "CreatedByNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Project_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Report", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Account", "CreatedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Report_CreatedBy");

                    b.HasOne("GithubReporterRepository.Models.Project", "Project")
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Project");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Student", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Account", "Account")
                        .WithMany("Students")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Student_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Supervisor", b =>
                {
                    b.HasOne("GithubReporterRepository.Models.Account", "Account")
                        .WithMany("Supervisors")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Supervisor_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Account", b =>
                {
                    b.Navigation("GroupTeams");

                    b.Navigation("Projects");

                    b.Navigation("Reports");

                    b.Navigation("Students");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Project", b =>
                {
                    b.Navigation("GradePerProjects");

                    b.Navigation("GroupTeams");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Student", b =>
                {
                    b.Navigation("GradePerProjects");
                });

            modelBuilder.Entity("GithubReporterRepository.Models.Supervisor", b =>
                {
                    b.Navigation("GroupTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
