// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class Account
{
    public Guid AccountId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Status { get; set; }

    public Guid RoleId { get; set; }

    public DateTime DateCreated { get; set; }

    public string GithubEmail { get; set; }

    public virtual ICollection<GroupTeam> GroupTeams { get; set; } = new List<GroupTeam>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual Student Student { get; set; }

    public virtual Supervisor Supervisor { get; set; }
}