// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GithubReporterRepository.Models;

public partial class GithubReporterContext : DbContext
{
    public GithubReporterContext(DbContextOptions<GithubReporterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<GradePerProject> GradePerProjects { get; set; }

    public virtual DbSet<GroupTeam> GroupTeams { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Supervisor> Supervisors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__349DA58681656706");

            entity.ToTable("Account");

            entity.Property(e => e.AccountId)
                .ValueGeneratedNever()
                .HasColumnName("AccountID");
            entity.Property(e => e.DateCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.GithubEmail).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
        });

        modelBuilder.Entity<GradePerProject>(entity =>
        {
            entity.HasKey(e => e.GradePerProjectId).HasName("PK__GradePer__8BEA86BD78158337");

            entity.ToTable("GradePerProject");

            entity.HasIndex(e => e.ProjectId, "IX_GradeOn_ProjectID");

            entity.HasIndex(e => e.StudentId, "IX_GradeOn_StudentID");

            entity.HasIndex(e => new { e.StudentId, e.ProjectId }, "UQ_GradePerProject_Student_Project").IsUnique();

            entity.Property(e => e.GradePerProjectId).ValueGeneratedNever();

            entity.HasOne(d => d.Project).WithMany(p => p.GradePerProjects)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GradePerProject_Project");

            entity.HasOne(d => d.Student).WithMany(p => p.GradePerProjects)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GradePerProject_Student");
        });

        modelBuilder.Entity<GroupTeam>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__GroupTea__149AF30A4B6EFCB0");

            entity.ToTable("GroupTeam");

            entity.HasIndex(e => e.ProjectId, "IX_Group_ProjectID");

            entity.Property(e => e.GroupId)
                .ValueGeneratedNever()
                .HasColumnName("GroupID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.GroupCode)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.SupervisorId).HasColumnName("SupervisorID");

            entity.HasOne(d => d.Account).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Group_Account");

            entity.HasOne(d => d.Project).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Group_Project");

            entity.HasOne(d => d.Supervisor).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.SupervisorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Group_Supervisor");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__Project__761ABED02637483E");

            entity.ToTable("Project");

            entity.HasIndex(e => e.CreatedBy, "IX_Project_CreatedBy");

            entity.Property(e => e.ProjectId)
                .ValueGeneratedNever()
                .HasColumnName("ProjectID");
            entity.Property(e => e.AccessToken).HasColumnType("text");
            entity.Property(e => e.DateCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.GithubLink).HasColumnType("text");
            entity.Property(e => e.ProjectName)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Projects)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Project_CreatedBy");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Report__D5BD48E5CDE90CBC");

            entity.ToTable("Report");

            entity.HasIndex(e => e.ProjectId, "IX_Report_ProjectID");

            entity.Property(e => e.ReportId)
                .ValueGeneratedNever()
                .HasColumnName("ReportID");
            entity.Property(e => e.DateCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.SupervisorComment).HasColumnType("text");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_CreatedBy");

            entity.HasOne(d => d.Project).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_Project");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Student__32C52A79ADB25055");

            entity.ToTable("Student");

            entity.Property(e => e.StudentId)
                .ValueGeneratedNever()
                .HasColumnName("StudentID");
            entity.Property(e => e.StudentCode)
                .IsRequired()
                .HasMaxLength(25);

            entity.HasOne(d => d.StudentNavigation).WithOne(p => p.Student)
                .HasForeignKey<Student>(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Account");
        });

        modelBuilder.Entity<Supervisor>(entity =>
        {
            entity.HasKey(e => e.SupervisorId).HasName("PK__Supervis__6FAABDAFB02DDE0A");

            entity.ToTable("Supervisor");

            entity.Property(e => e.SupervisorId)
                .ValueGeneratedNever()
                .HasColumnName("SupervisorID");
            entity.Property(e => e.SupervisorCode)
                .IsRequired()
                .HasMaxLength(25);

            entity.HasOne(d => d.SupervisorNavigation).WithOne(p => p.Supervisor)
                .HasForeignKey<Supervisor>(d => d.SupervisorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Supervisor_Account");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}