// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class GradePerProject
{
    public Guid GradePerProjectId { get; set; }

    public Guid StudentId { get; set; }

    public Guid ProjectId { get; set; }

    public int Grade { get; set; }

    public virtual Project Project { get; set; }

    public virtual Student Student { get; set; }
}