// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class GroupTeam
{
    public Guid GroupId { get; set; }

    public string GroupName { get; set; }

    public string GroupCode { get; set; }

    public Guid AccountId { get; set; }

    public int GroupRole { get; set; }

    public Guid ProjectId { get; set; }

    public Guid SupervisorId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Project Project { get; set; }

    public virtual Supervisor Supervisor { get; set; }
}