// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class Project
{
    public Guid ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string GithubLink { get; set; }

    public string Description { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime DateCreated { get; set; }

    public string AccessToken { get; set; }

    public virtual Account CreatedByNavigation { get; set; }

    public virtual ICollection<GradePerProject> GradePerProjects { get; set; } = new List<GradePerProject>();

    public virtual ICollection<GroupTeam> GroupTeams { get; set; } = new List<GroupTeam>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}