// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class Report
{
    public Guid ReportId { get; set; }

    public Guid ProjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime DateCreated { get; set; }

    public int CommitAmount { get; set; }

    public int ProgressByNumber { get; set; }

    public string SupervisorComment { get; set; }

    public virtual Account CreatedByNavigation { get; set; }

    public virtual Project Project { get; set; }
}