// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class Student
{
    public Guid StudentId { get; set; }

    public Guid AccountId { get; set; }

    public string StudentCode { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<GradePerProject> GradePerProjects { get; set; } = new List<GradePerProject>();
}