// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GithubReporterRepository.Models;

public partial class Supervisor
{
    public Guid SupervisorId { get; set; }

    public string SupervisorCode { get; set; }

    public virtual ICollection<GroupTeam> GroupTeams { get; set; } = new List<GroupTeam>();

    public virtual Account SupervisorNavigation { get; set; }
}